<?php include dirname(__DIR__). '../layouts/header.phtml'?>
<table>
    <thead>
        <tr>
            <th>Username</th>
            <th>Task</th>
            <th>Status</th>
            <th>Starting Date</th>
            <th>Finished Date</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td><?php ?></td>
            <td><?php ?></td>
            <td><?php ?></td>
            <td><?php ?></td>
            <td><?php ?></td>
            <td><?php ?></td>
        </tr>
    </tbody>
    <!-- <tfoot>

    </tfoot> -->
</table>
<?php include dirname(__DIR__). './layouts/footer.phtml'?>