<?php include dirname(__DIR__) . './views/layouts/header.phtml' ?>
<section>
    <table>
        <thead>
            <tr>
                <th>Username</th>
                <th>Task</th>
                <th>Status</th>
                <th>Starting Date</th>
                <th>Finished Date</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>
                    <?php ?>
                </td>
                <td>
                    <?php ?>
                </td>
                <td>
                    <?php ?>
                </td>
                <td>
                    <?php ?>
                </td>
                <td>
                    <?php ?>
                </td>
                <td>
                    <?php ?>
                </td>
            </tr>
        </tbody>
        <!-- <tfoot>

    </tfoot> -->
    </table>
</section>
<?php include dirname(__DIR__) . './views/layouts/footer.phtml' ?>