<?php include dirname(__DIR__).'\..\layouts\header.phtml';
require dirname(__DIR__) . '\..\models\persistence.php';
$task = $this->task_array;

var_dump($task);
?>
<form method="POST" action="" class="w-full max-w-sm">
    <div class="md:flex md:items-center mb-6">
        <div class="md:w-1/3">
            <label class="block text-gray-500 font-bold md:text-right mb-1 md:mb-0 pr-4" for="inline-username">
                Username
            </label>
        </div>
        <div class="md:w-2/3">
            <input
                class="text-grey-300 rounded shadow-md border-2 border-slate-100 hover:border-slate-200 focus:outline-none focus:border-[#F81BDC]"
                id="inline-full-name" type="text" value="<?php $task->username; ?>">
        </div>
    </div>
    <div class="md:flex md:items-center mb-6">
        <div class="md:w-1/3">
            <label class="block text-gray-500 font-bold md:text-right mb-1 md:mb-0 pr-4" for="inline-password">
                Task
            </label>
        </div>
        <div class="md:w-2/3">
            <input
                class="text-grey-300 rounded shadow-md border-2 border-slate-100 hover:border-slate-200 focus:outline-none focus:border-[#F81BDC]"
                id="inline-task" type="text" placeholder="<?php $task->task ?>">
        </div>
    </div>
    <div class="md:w-1/3">
            <label class="block text-gray-500 font-bold md:text-right mb-1 md:mb-0 pr-4" for="inline-status">
                Status
            </label>
        </div>
        <div class="md:w-2/3">
            <input
                class="text-grey-300 rounded shadow-md border-2 border-slate-100 hover:border-slate-200 focus:outline-none focus:border-[#F81BDC]"
                id="inline-full-name" type="text" value="<?php $task->status; ?>">
        </div>
    </div>
    <div class="md:flex md:items-center mb-6">
        <div class="md:w-1/3">
            <label class="block text-gray-500 font-bold md:text-right mb-1 md:mb-0 pr-4" for="inline-startedDate">
                Started Date
            </label>
        </div>
        <div class="md:w-2/3">
            <input
                class="text-grey-300 rounded shadow-md border-2 border-slate-100 hover:border-slate-200 focus:outline-none focus:border-[#F81BDC]"
                id="inline-task" type="text" placeholder="<?php $task->startedDate; ?>">
        </div>
    </div>
    <div class="md:w-1/3">
            <label class="block text-gray-500 font-bold md:text-right mb-1 md:mb-0 pr-4" for="inline-finishedDate">
                Finished Date
            </label>
        </div>
        <div class="md:w-2/3">
            <input
                class="text-grey-300 rounded shadow-md border-2 border-slate-100 hover:border-slate-200 focus:outline-none focus:border-[#F81BDC]"
                id="inline-full-name" type="text" value="<?php $task->finishedDate; ?>">
        </div>
    </div>
    <div class="md:flex md:items-center mb-6">
        <div class="md:flex md:items-center">
            <div class="md:w-1/3"></div>
            <div class="md:w-2/3">
                <button
                    class="col-span-1 p-1.5 text-white bg-[#F81BDC] hover:text-[#F81BDC] hover:bg-white rounded-full"
                    type="button">
                    Submit
                </button>
            </div>
        </div>
    </div>
</form>
<?php include dirname(__DIR__) . '\..\layouts\footer.phtml'; ?>