<?php include dirname(__DIR__) . '\..\layouts\header.phtml'; ?>

<div class="container p-2.5">
    <div class="flex justify-center place-content-center">
        <table class="divide-y divide-[#D5C2D5] border-2 border-collapse bg-[#F1C5F0]">
            <thead class="font-['Roboto'] divide-y divide-[#D5C2D5]">
                <tr>
                    <th class="p-1.5 text-white bg-[#F81BDC]">Username</th>
                    <th class="p-1.5 text-white bg-[#F81BDC]">Task</th>
                    <th class="p-1.5 text-white bg-[#F81BDC]">Status</th>
                    <th class="p-1.5 text-white bg-[#F81BDC]">Starting Date</th>
                    <th class="p-1.5 text-white bg-[#F81BDC]">Finished Date</th>
                    <th class="p-1.5 text-white bg-[#F81BDC]">Actions</th>
                </tr>
            </thead>
            <tbody class="divide-y divide-[#D5C2D5]">
                <?php foreach ($this->listTasks as $task): ?>
                    <tr>
                        <td>
                            <?php echo $task->getUsername(); ?>
                        </td>
                        <td>
                            <?php echo $task->getTask_name(); ?>
                        </td>
                        <td>
                            <?php echo $task->getStatus(); ?>
                        </td>
                        <td>
                            <?php echo $task->getStarting_date(); ?>
                        </td>
                        <td>
                            <?php echo $task->getFinished_date(); ?>
                        </td>
                        <td>
                            <div class="flex justify-center">
                                <div class="p-1.5 flex">
                                    <form action="viewTask" method="POST">
                                        <input type="hidden" name="task" value="<?php echo $task->getId(); ?>">
                                        <button
                                            class="w-[3rem] border-1 font-bold text-center text-white hover:text-[#F81BDC] bg-[#F81BDC] hover:bg-white hover:border-white rounded-full">View</button>
                                    </form>
                                </div>
                                <div class="p-1.5 flex">
                                    <form action="editTask" method="POST">
                                        <input type="hidden" name="task" value="<?php echo $task->getId(); ?>">
                                        <button
                                            class="w-[3rem] border-1 font-bold text-center text-white hover:text-[#F81BDC] bg-[#F81BDC] hover:bg-white hover:border-white rounded-full">Edit</button>
                                    </form>
                                </div>
                                <div class="p-1.5 flex">
                                    <form action="deleteTask" method="POST">
                                        <input type="hidden" name="task" value="<?php echo $task->getId(); ?>">
                                        <button
                                            class="w-[4.5rem] border-1 font-bold text-center text-white hover:text-[#F81BDC] bg-[#F81BDC] hover:bg-white rounded-full">Delete</button>
                                    </form>
                                </div>
                            </div>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>

<?php include dirname(__DIR__) . '\..\layouts\footer.phtml'; ?>
