<?php include dirname(__DIR__) . '\..\layouts\header.phtml'; ?>
<div class="container bg-slate-100 p-10 place-content-center rounded">
    <div class="p-5 bg-slate-300">
        <form action="addTask" method="POST">
            <input type="hidden" name="task" value="">
            <button onclick="'./application/addTask.phtml'"
                class="p-1.5 w-25 font-bold text-white text-m bg-[#F81BDC] hover:text-[#F81BDC] hover:bg-white rounded-full">Add
                Task</button>
        </form>
    </div>
    <div class="container bg-slate-200 place-content-center p-5">
        <table class="min-w-full divide-y divide-[#D5C2D5] border-2 border-separate bg-[#F1C5F0]">
            <thead class="font-['Roboto'] divide-y divide-[#D5C2D5]">
                <tr>
                    <th class="p-1.5 text-white bg-[#F81BDC]">Username</th>
                    <th class="p-1.5 text-white bg-[#F81BDC]">Task</th>
                    <th class="p-1.5 text-white bg-[#F81BDC]">Status</th>
                    <th class="p-1.5 text-white bg-[#F81BDC]">Starting Date</th>
                    <th class="p-1.5 text-white bg-[#F81BDC]">Finished Date</th>
                    <th class="p-1.5 text-white bg-[#F81BDC]">Actions</th>
                </tr>
            </thead>
            <tbody class="space-x-2 space-y-2 divide-y divide-[#D5C2D5] text-center">
                <?php foreach ($this->listTasks as $task): ?>
                    <tr class="divide-y divide-[#D5C2D5]">
                        <td>
                            <?php echo $task->username; ?>
                        </td>
                        <td>
                            <?php echo $task->task; ?>
                        </td>
                        <td>
                            <?php echo $task->status; ?>
                        </td>
                        <td>
                            <?php echo $task->startingDate; ?>
                        </td>
                        <td>
                            <?php echo $task->finishedDate; ?>
                        </td>
                        <td>
                            <div class="flex justify-center">
                                <div class="p-1.5 flex">
                                    <form action="viewTask" method="POST">
                                        <input type="hidden" name="task" value="<?php echo $task->getId(); ?>">
                                        <button
                                            class="w-[3rem] border-1 font-bold text-center text-white hover:text-[#F81BDC] bg-[#F81BDC] hover:bg-white hover:border-white rounded-full">View</button>
                                    </form>
                                </div>
                                <div class="p-1.5 flex">
                                    <form action="editTask" method="POST">
                                        <input type="hidden" name="task" value="<?php echo $task->getId(); ?>">
                                        <button
                                            class="w-[3rem] border-1 font-bold text-center text-white hover:text-[#F81BDC] bg-[#F81BDC] hover:bg-white hover:border-white rounded-full">Edit</button>
                                    </form>
                                </div>
                                <div class="p-1.5 flex">
                                    <form action="deleteTask" method="POST">
                                        <input type="hidden" name="task" value="<?php echo $task->getId(); ?>">
                                        <button
                                            class="w-[4.5rem] border-1 font-bold text-center text-white hover:text-[#F81BDC] bg-[#F81BDC] hover:bg-white rounded-full">Delete</button>
                                    </form>
                                </div>
                            </div>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>


<?php include dirname(__DIR__) . '\..\layouts\footer.phtml'; ?>