<?php include dirname(__DIR__) . '\..\layouts\header.phtml'; ?>

<div class="container p-10 mx-auto my-auto flex justify-center bg-slate-200">

    <div class="">
        <h3>Task Information: </h3>
    </div>
    <table class="min-w-full table-auto divide-y divide-[#D5C2D5] border-2 border-separate bg-[#F4EDF4]">
        <tbody>
            <tr>
                <th class="p-1.5 text-white bg-[#F81BDC]">Username:</th>
                <td>
                    <?php echo $this->task->username; ?>
                </td>
            </tr>
            <tr>
                <th class="p-1.5 text-white bg-[#F81BDC]">Task: </th>
                <td>
                    <?php echo $this->task->task; ?>
                </td>
            </tr>
            <tr>
                <th class="p-1.5 text-white bg-[#F81BDC]">Status: </th>
                <td>
                    <?php echo $this->task->status; ?>
                </td>
            </tr>
            <tr>
                <th class="p-1.5 text-white bg-[#F81BDC]">Started Date</th>
                <td>
                    <?php echo $this->task->startingDate; ?>
                </td>
            </tr>
            <tr>
                <th class="p-1.5 text-white bg-[#F81BDC]">Finished Date</th>
                <td>
                    <?php echo $this->task->finishedDate; ?>
                </td>
            </tr>
        </tbody>
    </table>
</div>
<?php include dirname(__DIR__) . '\..\layouts\footer.phtml'; ?>