<?php include dirname(__DIR__) . '\..\layouts\header.phtml'; ?>
<div class="container bg-slate-200 place-content-center p-5">
    <table class="min-w-full table-auto divide-y divide-[#D5C2D5] border-2 border-separate bg-[#F4EDF4]">
        <tbody>
            <tr>
                <th class="p-1.5 text-white bg-[#F81BDC]">Username:</th>
                <td>
                    <?php echo $task->username; ?>
                </td>
            </tr>
            <tr>
                <th class="p-1.5 text-white bg-[#F81BDC]">Task: </th>
                <td>
                    <?php echo $task->task; ?>
                </td>
            </tr>
            <tr>
                <th class="p-1.5 text-white bg-[#F81BDC]">Status: </th>
                <td>
                    <?php echo $task->status; ?>
                </td>
            </tr>
            <tr>
                <th class="p-1.5 text-white bg-[#F81BDC]">Started Date</th>
                <td>
                    <?php echo $task->startedDate; ?>
                </td>
            </tr>
            <tr>
                <th class="p-1.5 text-white bg-[#F81BDC]">Finished Date</th>
                <td>
                    <?php echo $task->finishedDate; ?>
                </td>
            </tr>
        </tbody>
    </table>
</div>
<?php include dirname(__DIR__) . '\..\layouts\footer.phtml'; ?>