</body>
<footer class="container p-10 mx-auto my-auto rounded bg-slate-100">
    <section class="grid grid-cols-4 bg-slate-200">
    	<div class="col-span-2">
          <p class="p-1.5"><span><i class="p-1.5 w-7 text-white bg-[#F81BDC] rounded-full fa fa-location-dot"></span></i> Roc Boronat, 117-127</p>
          <p class="p-1.5"><span><i class="p-1.5 w-7 text-white bg-[#F81BDC] rounded-full fa fa-phone"></span></i> 932 917 610</p>
          <p class="p-1.5"><span><i class="p-1.5 w-7 text-white bg-[#F81BDC] rounded-full fa fa-envelope"></span></i> cibernarium@barcelonactiva.cat</p>
     	</div>
        <div class="col-span-2 flex justify-end items-end content-end">
          <a href="https://www.instagram.com/barcelonactiva/"><i class="p-1.5 m-2 w-7 text-white bg-[#F81BDC] hover:text-[#F81BDC] hover:bg-white rounded-full fa-brands fa-instagram"></i>
          <a href="https://twitter.com/barcelonactiva"><i class="p-1.5 m-2 w-7 text-white bg-[#F81BDC] hover:text-[#F81BDC] hover:bg-white rounded-full fa-brands fa-square-twitter"></i>
          <a href="https://www.linkedin.com/company/barcelona-activa/"><i class="p-1.5 m-2 w-7 text-white bg-[#F81BDC] hover:text-[#F81BDC] hover:bg-white rounded-full fa-brands fa-linkedin"></i>
          <a href="https://www.facebook.com/barcelonactiva/"><i class="p-1.5 m-2 w-7 text-white bg-[#F81BDC] hover:text-[#F81BDC] hover:bg-white rounded-full fa-brands fa-facebook"></i>
          <a href="https://www.youtube.com/user/videosbarcelonactiva"><i class="p-1.5 m-2 w-7 text-white bg-[#F81BDC] hover:text-[#F81BDC] hover:bg-white rounded-full fa-brands fa-youtube"></i>
          <a href="https://www.slideshare.net/barcelonactiva"><i class="p-1.5 m-2 w-7 text-white bg-[#F81BDC] hover:text-[#F81BDC] hover:bg-white rounded-full fa-brands fa-slideshare"></i>
        </div>
    </section>
    <footer class="flex justify-center grid-col-4 col-span-4 p-4">&copy; IT Academy 2023</footer>
</footer>
</body>
</html>