<footer class="container grid-cols-4 gap-3 p-10 mx-auto my-auto rounded">
    <section class="flex justify-items-stretch grid grid-col-2 gap-1 col-span-2">
        <i class="col-span-1 p-1.5 w-7 text-white bg-[#F81BDC] rounded-full fa fa-location-dot"></i><p class="col-span-1">Roc Boronat, 117-127</p>
        <i class="col-span-1 p-1.5 w-7 text-white bg-[#F81BDC] rounded-full fa fa-phone"></i><p class="col-span-1">932 917 610</p>
        <i class="col-span-1 p-1.5 w-7 text-white bg-[#F81BDC] rounded-full fa fa-envelope"></i><p class="col-span-1">cibernarium@barcelonactiva.cat</p>
     	<a href="https://www.instagram.com/barcelonactiva/"><i class="p-1.5 w-7 text-white bg-[#F81BDC] hover:text-[#F81BDC] hover:bg-white rounded-full fa-brands fa-instagram"></i>
        <a href="https://twitter.com/barcelonactiva"><i class="p-1.5 w-7 text-white bg-[#F81BDC] hover:text-[#F81BDC] hover:bg-white rounded-full fa-brands fa-square-twitter"></i>
        <a href="https://www.linkedin.com/company/barcelona-activa/"><i class="p-1.5 w-7 text-white bg-[#F81BDC] hover:text-[#F81BDC] hover:bg-white rounded-full fa-brands fa-linkedin"></i>
        <a href="https://www.facebook.com/barcelonactiva/"><i class="p-1.5 w-7 text-white bg-[#F81BDC] hover:text-[#F81BDC] hover:bg-white rounded-full fa-brands fa-facebook"></i>
        <a href="https://www.youtube.com/user/videosbarcelonactiva"><i class="p-1.5 w-7 text-white bg-[#F81BDC] hover:text-[#F81BDC] hover:bg-white rounded-full fa-brands fa-youtube"></i>
        <a href="https://www.slideshare.net/barcelonactiva"><i class="p-1.5 w-7 text-white bg-[#F81BDC] hover:text-[#F81BDC] hover:bg-white rounded-full fa-brands fa-slideshare"></i>
    </section>
    <footer class="flex justify-center grid-col-4 col-span-4">&copy; IT Academy 2023</footer>
</footer>
</body>
</html>